" gvimrc

source ~/dotfiles/vim/vimrc

" window size
set lines=55
set columns=200

set winaltkeys=no

" guioption
set guioptions=M

set guioptions-=T
set guioptions-=m
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R
set guioptions-=b

set guioptions+=c
set guioptions+=e

" cursor
set cursorline
set cursorcolumn

" color
colorscheme hybrid

