" gvimrc

set encoding=utf-8
scriptencoding=utf-8

source ~/dotfiles/vim/vimrc

" window size
  set lines=70
  set columns=235

  set winaltkeys=no " altでメニューを掴まないようにする

" guioption
" NOTE:画面上部のメニューとか横のスクロールバーとかの設定
  set guioptions=M

  set guioptions-=T
  set guioptions-=m
  set guioptions-=l
  set guioptions-=L
  set guioptions-=r
  set guioptions-=R
  set guioptions-=b

  set guioptions+=c
  set guioptions+=e

" cursor
" NOTE:vimrcでwinならguiもcuiも無効にしてしまってるのでこちらプラス
  set cursorline
  set cursorcolumn

" color
  set t_Co=256 " guiでこの設定意味あるのかわかってない、無くても問題なく動作しそう
  colorscheme hybrid

" font
  set guifont=MS_Gothic:h10:cSHIFTJIS

