" gvimrc

source ~/dotfiles/vim/vimrc

set winaltkeys=no

set guioptions=M
set guioptions-=T
set guioptions-=m
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R
set guioptions-=b

set guioptions+=c
set guioptions+=e

colorscheme hybrid

