# bash_profile

# remove?
#if command -v keychain > /dev/null; then
#  eval $(keychain --eval --quiet)
#fi

f="$HOME"/dotfiles/shell/env
[ -f "$f" ] && source "$f"
unset f

[ -f "$HOME"/.bashrc ] && source "$HOME"/.bashrc

# vim:ft=sh:
