# zprofile

# umask
umask 022

# remove?
# keychain
#if command -v keychain > /dev/null; then
#  eval $(keychain --eval --quiet)
#fi

# environments
source "$HOME"/dotfiles/shell/share/env/locale.sh

# lang
source "$HOME"/dotfiles/shell/share/env/nodejs.sh
source "$HOME"/dotfiles/shell/share/env/go.sh
source "$HOME"/dotfiles/shell/share/env/ruby.sh
source "$HOME"/dotfiles/shell/share/env/rust.sh

# bin
[ -d "$HOME"/bin ] && export PATH="$HOME"/bin:"$PATH"

# completions
[ -d "$HOME"/dotfiles/shell/zsh/functions/completions ] && fpath+="$HOME"/dotfiles/shell/zsh/functions/completins

# rc
[ -f "$HOME"/.zshrc ] && source "$HOME"/.zshrc

