# zshrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# grml zshrc
# TODO: consider to remove
if command -v pacman &> /dev/null; then
  pacman -Q grml-zsh-config &> /dev/null ||
    echo "recommend: pacman -S grml-zsh-config"
fi

# alias
source "$HOME"/dotfiles/shell/alias

# setopt
setopt autocd
setopt autopushd
setopt pushdignoredups

# syntax highlight
f=/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
if [ -f "$f" ] && [ -r "$f" ]; then
  source "$f"
fi
unset f

# vim:ft=zsh:
