#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#twm &
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login

# for laptop
if xrandr --query | grep "HDMI1 connected" &> /dev/null; then
  xran="xrandr --output HDMI1 --primary --output LVDS1 --off"
fi

# for i3
if [ -d "$HOME"/Pictures/wall ]; then
  wall="$HOME"/Pictures/wall
  fehbg="feh --randomize --recursive --bg-max"
fi
if [ -r "$HOME"/.i3/compton.conf ]; then
  comp="compton --config"
  conf="$HOME"/.i3/compton.conf
fi

# fcitx
if true; then
  if [ -x /bin/fcitx-autostart ]; then
    fcitx-autostart
    export GTK_IM_MODULE=fcitx
    export QT_IM_MODULE=fcitx
    export XMODIFIERS=@im=fcitx
  fi
fi

# default session
session=${1:-i3}
case $session in
  i3|i3wm ) $xran & $fehbg "$wall" & $comp $conf & exec i3;;
  #i3-log|i3wm-log ) $xran & exec i3 -V -d all >> ~/.config/i3/i3log ;;
  #i3-log|i3wm-log ) $xran & exec i3 -V  >> ~/.config/i3/i3log 2>&1 ;;
  #i3-debug|i3wm-debug ) $xran & exec i3-with-shmlog;;
  #xfce|xfce4 ) $xran & exec startxfce4;;
  #plasma ) $xran & exec startkde;;
  #*) exec $1;;
  *) $xran & $fehbg "$wall" & $comp $conf & exec i3;;
esac
