#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# for laptop with broken screen
if xrandr --query | grep "HDMI1 connected" &> /dev/null; then
  xrandr="xrandr --output HDMI1 --primary --output LVDS1 --off"
fi

if true; then
  export LANG=ja_JP.UTF-8
  export LANGUAGE=ja_JP:en_US
  export LC_MESSAGES=C
else
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US
  export LC_MESSAGES=C
fi

# fcitx
if true; then
  if [ -x /bin/fcitx-autostart ]; then
    fcitx-autostart
    export GTK_IM_MODULE=fcitx
    export QT_IM_MODULE=fcitx
    export XMODIFIERS=@im=fcitx
  fi
fi

# for i3
unset fehbg wall
if [ -d "$HOME"/Pictures/wall ] &&  which feh &> /dev/null ; then
  fehbg="feh --randomize --recursive --bg-max"
  wall="$HOME"/Pictures/wall
fi
unset compton conf
if [ -r "$HOME"/.i3/compton.conf ] && which compton &> /dev/null ; then
  compton="compton --config"
  conf="$HOME"/.i3/compton.conf
fi

# default session
session=${1:-i3}
case $session in
  i3|i3wm ) $xrandr & $fehbg "$wall" & $compton "$conf" & exec i3;;
  #i3-log|i3wm-log ) $xran & exec i3 -V -d all >> ~/.config/i3/i3log ;;
  #xfce|xfce4 ) $xran & exec startxfce4;;
  #plasma ) $xran & exec startkde;;
  #*) exec $1;;
  *) $xrandr & $fehbg "$wall" & $compton "$conf" & exec i3;;
esac
