#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# disable display power management signaling
if [ -x /usr/bin/xset ]; then
  sleep 1 && xset s off r rate 200 30
fi
# for laptop with broken screen :P
if [ -x /usr/bin/xrandr ] && xrandr --query | grep "HDMI1 connected" &> /dev/null; then
  sleep 1 && xrandr --output HDMI1 --primary --auto --output LVDS1 --off
fi

# fcitx
if false; then
  if [ -x /usr/bin/fcitx-autostart ]; then
    export GTK_IM_MODULE=fcitx
    export QT_IM_MODULE=fcitx
    export XMODIFIERS="@im=fcitx"
    fcitx-autostart
  fi
fi

# TODO: reconsider ssh-agent
if [ -x /usr/bin/ssh-agent ]; then
  eval $(ssh-agent)
fi

# for i3
if [ -d "$HOME"/Pictures/links ] && [ -x /usr/bin/feh ]; then
  wallpath="$HOME"/Pictures/links
  fehbg="feh --bg-max"
  wall="$wallpath"/"$(ls "$wallpath" | shuf -n 1)"
fi
if [ -r "$HOME"/.i3/compton.conf ] && [ -x /usr/bin/compton ]; then
  compton="compton --config"
  conf="$HOME"/.i3/compton.conf
fi

# session
session="${1:-i3}"
case "$session" in
  i3|i3wm )
    $fehbg "$wall" &
    $compton "$conf" &
    exec /usr/bin/i3;;
  i3-log|i3wm-log )
    echo "xinit i3-log: $(date "+%Y-%m-%d")" > ~/.i3/i3.log
    $fehbg "$wall" &
    $compton "$conf" &
    exec /usr/bin/i3 -V -d all >> ~/.i3/i3.log;;
  * ) exec /usr/bin/i3;;
esac
