# zprofile


## define $DOTFILES_ROOT
source "$HOME"/dotfiles/share/dotenv.sh
if [ -z "$DOTFILES_ROOT" ]; then
  echo 'can not define $DOTFILES_ROOT'
  return
fi

# keychain
if command -v keychain > /dev/null; then
  eval $(keychain --eval --quiet)
fi

## environments
source "$DOTFILES_ROOT"/share/lang.sh
source "$DOTFILES_ROOT"/share/nodeenv.sh
source "$DOTFILES_ROOT"/share/goenv.sh
source "$DOTFILES_ROOT"/share/rubyenv.sh
### priority local bin
[ -d "$HOME"/bin ] && export PATH="$HOME"/bin:"$PATH"
[ -d "$HOME"/bin/dev ] && export PATH="$HOME"/bin/dev:"$PATH"
# EOF
