# zhsrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# lily
[[ "$(uname -n)" == "lily" ]] && echo "hello lily"

# define DOTFILES_ROOT
source $HOME/dotfiles/share/dotenv.bash
# environment
if [[ -n $DOTFILES_ROOT ]]; then
  # use grml zshrc, require don't move it
  if [[ "$(uname -a)" == "*\(ARCH\)\|\(arch\)*" ]] ; then
    source $DOTFILES_ROOT/zsh/zshrc.grml
  else
    echo "recommend: pacman -S grml-zsh-config"
  fi
  # TODO: add any env

  # golang
  source $DOTFILES_ROOT/share/goenv.bash

  # alias
  source $DOTFILES_ROOT/share/alias
else
  echo 'DOTFILES_ROOT=""'
fi

# setopt
setopt autocd
setopt autopushd
setopt pushdignoredups

# EOF
