#
# ~/.bash_profile
#

# umask
umask 022

# keychain
if command -v keychain > /dev/null; then
  eval $(keychain --eval --quiet)
fi

## environments
source "${HOME}"/dotfiles/share/lang.sh
source "${HOME}"/dotfiles/share/nodeenv.sh
source "${HOME}"/dotfiles/share/goenv.sh
source "${HOME}"/dotfiles/share/rubyenv.sh

### priority local bin
[ -d "${HOME}"/bin ] && export PATH="${HOME}"/bin:"${PATH}"

# call rc
[ -f "${HOME}"/.bashrc ] && source "${HOME}"/.bashrc
# EOF
