# bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# lily
[[ "$(uname -n)"=="lily" ]] && echo "hello lily"

# define DOTFILES_ROOT
source $HOME/dotfiles/share/dotenv.bash

# environment
if [[ "$DOTFILES_ROOT"!="" ]]; then
  # TODO: add any env

  # completion
  source $DOTFILES_ROOT/bash/bash_completion_tmux.sh

  # golang
  source $DOTFILES_ROOT/share/goenv.bash

  # alias
  source $DOTFILES_ROOT/share/alias
else
  echo 'DOTFIILES_ROOT=""'
fi

# call zsh
if [[ -x /bin/zsh ]]; then
  if [[ $SHLVL -eq 1 ]]; then
    /bin/zsh
  fi
else
  # remind
  echo ""
fi
# EOF
