# bashrc

# define DOTFILES_ROOT
source $HOME/dotfiles/share/dotenv.sh

# environment
if [[ "$DOTFILES_ROOT" != "" ]]; then

  # TODO:add any env

  # function
  source $DOTFILES_ROOT/bash/function/jisho

  # pompletion
  source $DOTFILES_ROOT/share/bash_completion_tmux.sh

  # golang
  source $DOTFILES_ROOT/share/goenv.sh

  # alias
  source $DOTFILES_ROOT/share/alias
  source $DOTFILES_ROOT/bash/alias
else
  echo 'DOTFIILES_ROOT=""'
fi


# 環境変数の設定はrcでは登録せず
# functionをsourceしておいて必要に応じて呼ぶようにするべき?
# 取り敢えずbashrcで呼ぶようにしておく

# call zsh
if [[ -x /bin/zsh ]]; then
  if [[ $SHLVL -eq 1 ]]; then
    /bin/zsh
  fi
else
  echo 'not found zsh'
fi

echo "exit zsh"
# EOF
